### ISSUE TITLE
Int vs Float

### ISSUE THREAD

**Issue by mattboutet** [BigRoomStudios/schwifty-migration#5]
If I have `Joi.number()` in my `joiSchema`, it seems like schwifty-migration should assume it's floating point, since Joi provides `.integer()` to specify ints, but nothing similar for floating point numbers.

**Comment by wswoodruff** [comment]
Fixed in https://github.com/BigRoomStudios/schwifty-migration/commit/3f1e9e417fd709ebbec309771b5c3aad92470699
